### ISSUE TITLE
字体颜色 边框 内边距 等等这些都没有？

### ISSUE THREAD

**Issue by mickey0085** [ydcss/ydui#7]
## 问题描述 

上线时间也不短了，先不说JS 组件，CSS 基础部分，缺少很多，字体颜色啊、边框啊
内边距、外边距、甚至 布局功能都没有，只有一个九宫格，列表样式也少的可怜，只有一个商品信息样式的列表样式。。 顶部的 点击打开侧边栏，点击下拉菜单，这些基础的功能都没增加。不知道作者怎么考虑的？如果使用你这个 框架。还得自己大量定义很多东西。。非常不方便。

**Comment by mickey0085** [comment]
可是我就是想用你做的这个咋办啊。。。

**Comment by ydcss** [comment]
不懂你什么用意，为了评论特意注册了github账号。
YDUI提供了订制工具，颜色什么的都可以订制。
通过订制工具可以只选择你喜欢的组件，完全可以与其他框架什么的一同使用。
我一人同时维护两个项目，时间精力有限，存在问题在所难免，缺少什么功能，也没见你提，而是一味抱怨。
所以建议你去看看SUI，MUI，WEUI等上线时间长且高大上的框架。
